GH action summary added for e2e test
observermedia/eight-day-week pull request #119
Opened 2023-06-21 16:46 UTC by jayedul

### Description of the Change
GH action summary added Cypress test report

Closes #106  

### Changelog Entry

> Added - GH action summary added Cypress test report

### Credits

Props @jayedul 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

2023-06-21 17:16 UTC, jayedul commented
This PR has been marked as ready for review though one action is failing which is unrelated tho this PR in fact.

2023-06-22 05:49 UTC, ravinderk commented on tests/cypress/config.js
> +    reportDir: __dirname+"/reports",
@jayedul Can we hard code the relative path to main consistency? as we are doing in https://github.com/10up/cypress-wp-utils/pull/63/files#diff-c6bacf338af5eaa9a6bd78b3183be542f3b59859910a1c48214c01288b7d8431R13

2023-06-22 05:52 UTC, ravinderk requested changes
@jayedul I left a suggestion.

Questions:
Did you run this workflow on the fork to test? Can you provide a link?

2023-06-30 06:35 UTC, jayedul commented
@ravinderk I've run it locally. And it is generating the report as expected. No shareable link for now as  it is not deployed anywhere else. 
<img width="3008" alt="Screenshot 2023-06-30 at 12 30 39 PM" src="https://github.com/10up/eight-day-week/assets/12506700/b52a138b-2ebd-4d43-bbde-d2869d6c1d58">

2023-06-30 07:08 UTC, ravinderk approved these changes

2023-06-30 17:45 UTC, merged