Feature/cypress test
observermedia/eight-day-week pull request #148
Opened 2024-06-07 16:31 UTC by sudip-md

###Local Test Result
![TestResult](https://github.com/10up/eight-day-week/assets/94599521/3bbf5d66-e3f2-465d-8324-097298d39d14)

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-09-06 12:36 UTC, iamdharmesh requested changes
Hi @sudip-md, Thanks for adding additional tests and raising a PR. I have updated the initialize script to fix tests failing in the GH action environment. However, I have added 2 notes on the PR. Could you please help with checking on those? Once it is resolved, we will be able to merge this.

Thank you.

2024-09-06 12:36 UTC, iamdharmesh commented on tests/cypress/e2e/article-status.test.js
> +        cy.get('#submit').click();
We might want to add a verification step here to confirm that the article status was created successfully.

2024-09-06 12:36 UTC, iamdharmesh commented on tests/cypress/e2e/article-status.test.js
> +        cy.get('.button').click();
Same as above, Add a verification step to confirm status edited successfully. Could you please help to add verification steps for all the tests?

2024-10-16 01:10 UTC, jeffpaul commented on tests/cypress/e2e/article-status.test.js
> +        cy.get('#submit').click();
@iamdharmesh probably best if you help get things updated for this PR and merge in

2025-03-13 16:26 UTC, jeffpaul commented
The latest commit adds verification steps to all three test cases to ensure proper validation of the operations:

1. Create Article Status:
   - Verifies success message "Article Status added."
   - Confirms the new status appears in the list

2. Edit Article Status:
   - Verifies success message "Article Status updated."
   - Confirms the edited status appears in the list

3. Delete Article Status:
   - Verifies success message "Article Status deleted."
   - Confirms the status is removed from the list

These changes ensure we're properly validating the success of each operation and the UI reflects the expected changes. The tests will now fail if any operation doesn't complete successfully or if the UI doesn't update as expected.

(thanks Cursor! ;)

2025-03-31 05:57 UTC, iamdharmesh approved these changes

2025-03-31 05:57 UTC, merged